### PR TITLE
Create FAQ Section and Add Routing for FAQ pages

### PR DESCRIPTION
**Pull request by abdulr07**

### CODE REVIEW

**Comment by chrisgumieny** [comment]
Great additions! Everything looks good.

**Review by chrisgumieny — DISMISSED** [review]
Great changes, everything looks good!

**Review by IKwiotek — CHANGES_REQUESTED** [review]
These changes look great, but I want to reorganize the file structure before we merge these changes into the `main` branch.

**Comment by IKwiotek** [comment]
I deployed these updates to the hosted site. Unfortunately, it did not compile due to the [src/components/FAQ/Faq.css](https://github.com/WSU-4110/Crypto/pull/39/files#diff-9a2e203b680c6f0fac71a4e77e5cb5b20d34ddace7998131e1a9b86651c4ddb8) page. I do not have an explanation currently of how `.css` files should be compiled into a React application.

#### A Quick Fix 
You could utilize the accordion @chrisgumieny implemented for the [FirstPartyEducation.js](https://github.com/WSU-4110/Crypto/blob/main/src/components/FirstPartyEducation.js) page.

**Comment by IKwiotek** [comment]
@abdulr07 

Does the content in [src/components/FAQ/Faq.json](https://github.com/WSU-4110/Crypto/pull/39/files#diff-b45f9c2910489a692eeb84b673244da8346213fa6c99699f304990c1b118be7e) meet the requirements for https://github.com/WSU-4110/Crypto/issues/21 ?

_When a user enters the website they will have an option to navigate to a page that outlines the product’s FAQ / User Documentation. This documentation will include basic user information such as creating an account, performing basic actions, and possibly some information regarding upcoming features. This page will allow new users to obtain an understanding of how to use the website quickly and easily._

The content in [src/components/FAQ/Faq.json](https://github.com/WSU-4110/Crypto/pull/39/files#diff-b45f9c2910489a692eeb84b673244da8346213fa6c99699f304990c1b118be7e) seems to be closer to the requirements for https://github.com/WSU-4110/Crypto/issues/16 found in [FirstPartyEducation.js](https://github.com/WSU-4110/Crypto/blob/main/src/components/FirstPartyEducation.js).

### Possible Q/A's
- How to Create an Account?
- How to Change & Reset Password?
- What can be found on the FirstPartyEducation page?
- What can be found on the ThirdPartyEducation page?

Additionally, this page will evolve as additional functionality is added to the website.

**Review by vionaveseli — CHANGES_REQUESTED** [review]
FAQ needs to talk about how to use the website not info about crypto (that is first party education). check https://github.com/WSU-4110/Crypto/issues/21 for more info

**Review by IKwiotek — CHANGES_REQUESTED** [review]
Overall the updates look good and the new QA's are in line with the issue requirements. The first QA can be omitted as it is similar to the first A in FirstPartyEducation. Other crypto-QA not related to site functionality can also be omitted.

The .css file should be removed for now as it breaks the hosted site. Following the FirstPartyEducation should allow for basic accordion-style rendering.

**Review by vionaveseli — APPROVED** [review]
looks good. I like that its /help instead of /FAQ it makes more sense this way. Good job!

**Review by IKwiotek — APPROVED** [review]
The information reflects the associated issue, and the formatting is consistent with recent changes. Approving!

**Pull request merged**
